language: java
jdk: oraclejdk8
# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

before_install:
  # Disable all Travis default repositories
  - sed -i "s/activeByDefault>true</activeByDefault>false</g"  ~/.m2/settings.xml

script:
  # TRAVIS_PULL_REQUEST == "false" for a normal branch commit, the PR number for a PR
  # TRAVIS_BRANCH == target of normal commit or target of PR
  # TRAVIS_SECURE_ENV_VARS == true if encrypted variables are available
  # TRAVIS_REPO_SLUG == the repository, e.g. vaadin/framework8-demo
  # TESTBENCH_LICENSE == TB4 license, defined as a secure variable in .travis.yml

  if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]
  then
	  # Secure vars available, needed for TestBench tests
	  # Pull request inside repository or branch build
	  mvn -B -e -V -Dvaadin.testbench.developer.license=$TESTBENCH_LICENSE -Pintegration-tests verify
  fi

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/flow
  - rm -rf $HOME/.m2/repository/com/vaadin/flow-*
